# This is a basic workflow to help you get started with Actions

name: CI

on:
  repository_dispatch:
    types: ["release-event"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Run a one-line script
      run: echo Hello, world!
