name: Repository Dispatch
on:
  repository_dispatch:
    types: ['release-event']
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo ${{ github.event.client_payload }}
